name: C/C++ CI

on: [push, pull_request]

jobs:
  windows:
    name: 'Windows'
    runs-on: windows-latest
    
    env:
     solution: 'vs-project/bspguy.sln'

    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
            fetch-depth: 0
            submodules: true

     - name: Add msbuild to PATH
       uses: microsoft/setup-msbuild@v1.1
       with:
            vs-prerelease: true

     - name: Build app for release
       run: msbuild ${{ env.solution }} -m -t:rebuild -verbosity:diag -property:Configuration=Release

     - name: Artifact1
       uses: actions/upload-artifact@v3
       with:
         name: Windows
         path: ./vs-project/Release/bspguy.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Download and install dependencies
      run: |
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev libglew-dev libxxf86vm-dev

    - name: Build release
      run: |
        mkdir build; cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bspguy-linux
        path: build/bspguy
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: build/bspguy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}