name: C/C++ CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build release 
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bspguy-windows
        path: build/Release

  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Download and install dependencies
      run: |
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev libglew-dev libxxf86vm-dev

        wget https://github.com/ocornut/imgui/archive/refs/tags/v1.81.zip

        unzip -q v1.81.zip

        mv imgui-1.81 imgui

    - name: Build release
      run: |
        mkdir build; cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bspguy-linux
        path: build/bspguy
